# Generated by Django 5.2.18 on 2026-10-07 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rapport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("requete", "Requête KPI"),
                            ("evenement", "Événement"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pptx", "PowerPoint"), ("xlsx", "Excel")],
                        max_length=8,
                    ),
                ),
                ("parametres", models.JSONField(default=dict)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("erreur", "Erreur"),
                        ],
                        default="en_attente",
                        max_length=16,
                    ),
                ),
                ("fichier", models.FileField(blank=True, upload_to="rapports/%Y/%m/")),
                ("message", models.TextField(blank=True)),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "termine_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="terminé le"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-cree_le"],
            },
        ),
    ]
