# Generated by Django 5.2.18 on 2026-10-09 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rapports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportPlanifie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                (
                    "requete",
                    models.JSONField(
                        help_text="RequeteKpi ; sa période est recalculée à chaque lancement."
                    ),
                ),
                (
                    "periode",
                    models.CharField(
                        choices=[
                            ("hier", "Hier"),
                            ("7j", "7 derniers jours"),
                            ("semaine_derniere", "Semaine dernière"),
                            ("30j", "30 derniers jours"),
                            ("mois_dernier", "Mois dernier"),
                            ("mois_courant", "Ce mois-ci"),
                        ],
                        default="7j",
                        max_length=20,
                        verbose_name="période",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pptx", "PowerPoint"), ("xlsx", "Excel")],
                        default="pptx",
                        max_length=8,
                    ),
                ),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("aucune", "Sur demande"),
                            ("quotidienne", "Chaque jour"),
                            ("hebdomadaire", "Chaque semaine"),
                            ("mensuelle", "Chaque mois (le 1er)"),
                        ],
                        default="aucune",
                        max_length=16,
                        verbose_name="fréquence",
                    ),
                ),
                (
                    "jour_semaine",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        default=0,
                        verbose_name="jour",
                    ),
                ),
                (
                    "heure",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "0 h"),
                            (1, "1 h"),
                            (2, "2 h"),
                            (3, "3 h"),
                            (4, "4 h"),
                            (5, "5 h"),
                            (6, "6 h"),
                            (7, "7 h"),
                            (8, "8 h"),
                            (9, "9 h"),
                            (10, "10 h"),
                            (11, "11 h"),
                            (12, "12 h"),
                            (13, "13 h"),
                            (14, "14 h"),
                            (15, "15 h"),
                            (16, "16 h"),
                            (17, "17 h"),
                            (18, "18 h"),
                            (19, "19 h"),
                            (20, "20 h"),
                            (21, "21 h"),
                            (22, "22 h"),
                            (23, "23 h"),
                        ],
                        default=7,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "prochain_lancement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="prochain lancement"
                    ),
                ),
                (
                    "dernier_lancement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernier lancement"
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_planifies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "rapport enregistré",
                "verbose_name_plural": "rapports enregistrés",
                "ordering": ["titre"],
            },
        ),
        migrations.AddField(
            model_name="rapport",
            name="planification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rapports",
                to="rapports.rapportplanifie",
                verbose_name="rapport enregistré",
            ),
        ),
    ]
