# Generated by Django 5.2.18 on 2026-10-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rapports", "0003_tache_rapports_planifies"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rapport",
            options={
                "ordering": ["-cree_le"],
                "verbose_name": "rapport généré",
                "verbose_name_plural": "rapports générés",
            },
        ),
    ]
