# Generated by Django 5.2.18 on 2026-10-06 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(max_length=64)),
                ("requete", models.JSONField(blank=True, default=dict)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "entrée du journal d'audit",
                "verbose_name_plural": "journal d'audit",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Perimetre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=128, unique=True)),
                ("communes", models.JSONField(blank=True, default=list)),
                (
                    "sites",
                    models.JSONField(
                        blank=True, default=list, verbose_name="codes site"
                    ),
                ),
                ("cellules", models.JSONField(blank=True, default=list)),
                (
                    "kpis_autorises",
                    models.JSONField(
                        blank=True, default=list, verbose_name="KPI autorisés"
                    ),
                ),
                (
                    "groupes",
                    models.ManyToManyField(
                        blank=True, related_name="perimetres", to="auth.group"
                    ),
                ),
                (
                    "utilisateurs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="perimetres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "périmètre",
            },
        ),
    ]
