# Generated by Django 5.2.18 on 2026-10-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perimetre",
            options={
                "verbose_name": "périmètre d'accès",
                "verbose_name_plural": "périmètres d'accès",
            },
        ),
    ]
