# Generated by Django 5.2.18 on 2026-10-06 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_site",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="code site"
                    ),
                ),
                ("trigramme", models.CharField(db_index=True, max_length=8)),
                ("nom", models.CharField(max_length=64)),
                ("commune", models.CharField(db_index=True, max_length=64)),
                (
                    "region",
                    models.CharField(blank=True, max_length=32, verbose_name="région"),
                ),
                (
                    "nom_wcdma",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="nom RBS 3G"
                    ),
                ),
                (
                    "nom_lte",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="nom ERBS"
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "type_zone",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="type de zone"
                    ),
                ),
            ],
            options={
                "ordering": ["code_site"],
            },
        ),
        migrations.CreateModel(
            name="ImportReferentiel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("fichier", models.CharField(max_length=255)),
                ("nb_sites", models.PositiveIntegerField(default=0)),
                ("nb_secteurs", models.PositiveIntegerField(default=0)),
                ("ajouts", models.JSONField(blank=True, default=list)),
                ("suppressions", models.JSONField(blank=True, default=list)),
                ("anomalies", models.JSONField(blank=True, default=list)),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "import du référentiel",
                "verbose_name_plural": "imports du référentiel",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("numero", models.PositiveSmallIntegerField(verbose_name="n° secteur")),
                ("azimut", models.SmallIntegerField(blank=True, null=True)),
                ("province", models.CharField(blank=True, max_length=16)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secteurs",
                        to="referentiel.site",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Cellule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=32)),
                (
                    "techno",
                    models.CharField(
                        choices=[("LTE", "LTE"), ("WCDMA", "WCDMA")], max_length=8
                    ),
                ),
                ("porteuse", models.PositiveSmallIntegerField(default=0)),
                (
                    "secteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cellules",
                        to="referentiel.secteur",
                    ),
                ),
            ],
            options={
                "ordering": ["techno", "nom"],
                "unique_together": {("techno", "nom")},
            },
        ),
    ]
