# Generated by Django 5.2.18 on 2026-10-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referentiel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="nb_secteurs",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="nb secteurs"
            ),
        ),
    ]
