# Generated by Django 5.2.18 on 2026-10-09 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referentiel", "0002_site_nb_secteurs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secteur",
            name="azimut",
        ),
        migrations.RemoveField(
            model_name="secteur",
            name="province",
        ),
        migrations.AddField(
            model_name="cellule",
            name="secteur_avant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cellules_avant_bascule",
                to="referentiel.secteur",
                verbose_name="secteur avant passage à 4 secteurs",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="bascule_4_secteurs",
            field=models.DateField(
                blank=True,
                help_text="Premier jour en 4 secteurs (cf. manage.py detecter_bascules).",
                null=True,
                verbose_name="passage à 4 secteurs",
            ),
        ),
    ]
