# Generated by Django 5.2.18 on 2026-10-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeuilKpi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="KPI"),
                ),
                ("alerte", models.FloatField(blank=True, null=True)),
                ("critique", models.FloatField(blank=True, null=True)),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
            ],
            options={
                "verbose_name": "seuil KPI",
                "verbose_name_plural": "seuils KPI",
                "ordering": ["code"],
            },
        ),
    ]
