# Generated by Django 5.2.18 on 2026-10-07 03:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglagesAnomalies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ecart_sigma",
                    models.FloatField(
                        default=2.0, verbose_name="écart : nombre d'écarts-types"
                    ),
                ),
                (
                    "ecart_pct",
                    models.FloatField(
                        default=20.0,
                        verbose_name="écart : % minimal par rapport à la référence",
                    ),
                ),
                (
                    "saturation_prb",
                    models.FloatField(
                        default=90.0,
                        verbose_name="saturation : PRB DL au-dessus de (%)",
                    ),
                ),
                (
                    "saturation_debit",
                    models.FloatField(
                        default=10.0,
                        verbose_name="saturation : débit DL en dessous de (Mbps)",
                    ),
                ),
            ],
            options={
                "verbose_name": "réglages de détection d'anomalies",
                "verbose_name_plural": "réglages de détection d'anomalies",
            },
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Étiquette libre, ex. Concert, Journée, Foire.",
                        max_length=32,
                    ),
                ),
                (
                    "sites",
                    models.JSONField(
                        blank=True, default=list, verbose_name="codes site"
                    ),
                ),
                ("secteurs", models.JSONField(blank=True, default=list)),
                ("cellules", models.JSONField(blank=True, default=list)),
                (
                    "kpis",
                    models.JSONField(
                        blank=True, default=list, verbose_name="KPI analysés"
                    ),
                ),
                (
                    "semaines_reference",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Chaque créneau est comparé aux mêmes jour et heures des N semaines précédentes.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="semaines de référence",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "événement",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Creneau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debut", models.DateTimeField(verbose_name="début")),
                ("fin", models.DateTimeField()),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creneaux",
                        to="evenements.evenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "créneau",
                "ordering": ["debut"],
            },
        ),
    ]
