# Generated by Django 5.2.18 on 2026-10-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creneau",
            options={
                "ordering": ["debut"],
                "verbose_name": "créneau",
                "verbose_name_plural": "créneaux",
            },
        ),
    ]
